name: hive_generator
description: Extension for Hive. Automatically generates TypeAdapters to store any class.
version: 1.1.1
homepage: https://github.com/hivedb/hive/tree/master/hive_generator
documentation: https://docs.hivedb.dev/

publish_to: 'none'

environment:                                                            
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build: ^2.4.1
  source_gen: ^1.5.0
  hive:
    git:
      url: ../
      ref: xal/nested_type_registry_dev
      path: hive
    # path: ../../../packages/hive/hive
  analyzer: ^6.4.1
  source_helper: ^1.3.4

dev_dependencies:
  test: ^1.25.5
  build_test: 2.2.2
  build_runner: 2.4.9
  pedantic: ^1.11.1
  