name: fediverse_api_login_cmd
version: 1.0.9

description: Common code for all fediverse_api_login_cmd extension packages
homepage: https://github.com/Big-Fig/Fediverse.app
repository: https://github.com/Big-Fig/Fediverse.app

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  easy_dispose: ^1.1.0
  puppeteer: ^3.9.0
  http: ^1.2.1
  args: ^2.5.0
  logging: ^1.2.0
  fediverse_api:
    path: ../../packages/fediverse_api
#    git:
#      url: https://github.com/Big-Fig/Fediverse.app.git
#      path: packages/fediverse_api
  freezed_annotation: ^2.4.1


dev_dependencies:
  # test utils
  test: ^1.25.2
  # mock utils
  mockito: ^5.4.4
  # additional linters
  # dart_code_metrics: ^4.5.0
  lints: 4.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.9
  # helper to specify all rules in one line
  all_lint_rules_community: ^0.0.40