// Mocks generated by Mockito 5.4.4 from annotations
// in fedi_app/test/app/account/account_bloc_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:easy_dispose/easy_dispose.dart' as _i9;
import 'package:fediverse_api/fediverse_api.dart' as _i7;
import 'package:fediverse_api/fediverse_api_utils.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:unifedi_api/src/api/account/identity_proof/unifedi_api_account_identity_proof_model.dart'
    as _i16;
import 'package:unifedi_api/src/api/account/register/response/unifedi_api_register_account_response_model.dart'
    as _i6;
import 'package:unifedi_api/src/api/account/register/unifedi_api_register_account_model.dart'
    as _i17;
import 'package:unifedi_api/src/api/account/relationship/unifedi_api_account_relationship_model.dart'
    as _i5;
import 'package:unifedi_api/src/api/account/service/unifedi_api_account_service.dart'
    as _i10;
import 'package:unifedi_api/src/api/account/unifedi_api_account_model.dart'
    as _i4;
import 'package:unifedi_api/src/api/feature/unifedi_api_feature_model.dart'
    as _i2;
import 'package:unifedi_api/src/api/list/unifedi_api_list_model.dart' as _i15;
import 'package:unifedi_api/src/api/pagination/unifedi_api_pagination_model.dart'
    as _i14;
import 'package:unifedi_api/src/api/rest/unifedi_api_rest_service.dart' as _i3;
import 'package:unifedi_api/src/api/status/unifedi_api_status_model.dart'
    as _i12;
import 'package:unifedi_api/src/api/visibility/unifedi_api_visibility_sealed.dart'
    as _i13;
import 'package:unifedi_api/src/api/web_sockets/event/unifedi_api_web_sockets_event_model.dart'
    as _i19;
import 'package:unifedi_api/src/api/web_sockets/unifedi_api_web_sockets_service.dart'
    as _i18;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIUnifediApiFeature_0 extends _i1.SmartFake
    implements _i2.IUnifediApiFeature {
  _FakeIUnifediApiFeature_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIUnifediApiRestService_1 extends _i1.SmartFake
    implements _i3.IUnifediApiRestService {
  _FakeIUnifediApiRestService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIUnifediApiAccount_2 extends _i1.SmartFake
    implements _i4.IUnifediApiAccount {
  _FakeIUnifediApiAccount_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIUnifediApiAccountRelationship_3 extends _i1.SmartFake
    implements _i5.IUnifediApiAccountRelationship {
  _FakeIUnifediApiAccountRelationship_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIUnifediApiRegisterAccountResponse_4 extends _i1.SmartFake
    implements _i6.IUnifediApiRegisterAccountResponse {
  _FakeIUnifediApiRegisterAccountResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFediverseApiFeatureRequirementState_5 extends _i1.SmartFake
    implements _i7.FediverseApiFeatureRequirementState {
  _FakeFediverseApiFeatureRequirementState_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIWebSocketsService_6 extends _i1.SmartFake
    implements _i8.IWebSocketsService {
  _FakeIWebSocketsService_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIDisposable_7 extends _i1.SmartFake implements _i9.IDisposable {
  _FakeIDisposable_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IUnifediApiAccountService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIUnifediApiAccountService extends _i1.Mock
    implements _i10.IUnifediApiAccountService {
  MockIUnifediApiAccountService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IUnifediApiFeature get getAccountStatusesFeature => (super.noSuchMethod(
        Invocation.getter(#getAccountStatusesFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getAccountStatusesFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getAccountStatusesWithMutedFeature =>
      (super.noSuchMethod(
        Invocation.getter(#getAccountStatusesWithMutedFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getAccountStatusesWithMutedFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getAccountStatusesExcludeVisibilitiesFeature =>
      (super.noSuchMethod(
        Invocation.getter(#getAccountStatusesExcludeVisibilitiesFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getAccountStatusesExcludeVisibilitiesFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getAccountStatusesPaginationMinIdFeature =>
      (super.noSuchMethod(
        Invocation.getter(#getAccountStatusesPaginationMinIdFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getAccountStatusesPaginationMinIdFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getAccountStatusesExcludeReblogsFeature =>
      (super.noSuchMethod(
        Invocation.getter(#getAccountStatusesExcludeReblogsFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getAccountStatusesExcludeReblogsFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getAccountStatusesTaggedFeature =>
      (super.noSuchMethod(
        Invocation.getter(#getAccountStatusesTaggedFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getAccountStatusesTaggedFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getAccountFavouritedStatusesFeature =>
      (super.noSuchMethod(
        Invocation.getter(#getAccountFavouritedStatusesFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getAccountFavouritedStatusesFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getAccountFeature => (super.noSuchMethod(
        Invocation.getter(#getAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getAccountWithRelationshipFeature =>
      (super.noSuchMethod(
        Invocation.getter(#getAccountWithRelationshipFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getAccountWithRelationshipFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getRelationshipWithAccountsFeature =>
      (super.noSuchMethod(
        Invocation.getter(#getRelationshipWithAccountsFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getRelationshipWithAccountsFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get searchFeature => (super.noSuchMethod(
        Invocation.getter(#searchFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#searchFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getListsWithAccountFeature => (super.noSuchMethod(
        Invocation.getter(#getListsWithAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getListsWithAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getAccountIdentifyProofsFeature =>
      (super.noSuchMethod(
        Invocation.getter(#getAccountIdentifyProofsFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getAccountIdentifyProofsFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get followAccountFeature => (super.noSuchMethod(
        Invocation.getter(#followAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#followAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get followAccountNotifyFeature => (super.noSuchMethod(
        Invocation.getter(#followAccountNotifyFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#followAccountNotifyFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get unFollowAccountFeature => (super.noSuchMethod(
        Invocation.getter(#unFollowAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#unFollowAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get pinAccountFeature => (super.noSuchMethod(
        Invocation.getter(#pinAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#pinAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get unPinAccountFeature => (super.noSuchMethod(
        Invocation.getter(#unPinAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#unPinAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get muteAccountFeature => (super.noSuchMethod(
        Invocation.getter(#muteAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#muteAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get unMuteAccountFeature => (super.noSuchMethod(
        Invocation.getter(#unMuteAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#unMuteAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get subscribeAccountFeature => (super.noSuchMethod(
        Invocation.getter(#subscribeAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#subscribeAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get unSubscribeAccountFeature => (super.noSuchMethod(
        Invocation.getter(#unSubscribeAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#unSubscribeAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get blockAccountFeature => (super.noSuchMethod(
        Invocation.getter(#blockAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#blockAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get unBlockAccountFeature => (super.noSuchMethod(
        Invocation.getter(#unBlockAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#unBlockAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get blockDomainFeature => (super.noSuchMethod(
        Invocation.getter(#blockDomainFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#blockDomainFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get unBlockDomainFeature => (super.noSuchMethod(
        Invocation.getter(#unBlockDomainFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#unBlockDomainFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get noteFeature => (super.noSuchMethod(
        Invocation.getter(#noteFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#noteFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get reportAccountFeature => (super.noSuchMethod(
        Invocation.getter(#reportAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#reportAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get reportAccountForwardFeature => (super.noSuchMethod(
        Invocation.getter(#reportAccountForwardFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#reportAccountForwardFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getAccountFollowingsFeature => (super.noSuchMethod(
        Invocation.getter(#getAccountFollowingsFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getAccountFollowingsFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getAccountFollowersFeature => (super.noSuchMethod(
        Invocation.getter(#getAccountFollowersFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getAccountFollowersFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getAccountFollowingsWithRelationshipFeature =>
      (super.noSuchMethod(
        Invocation.getter(#getAccountFollowingsWithRelationshipFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getAccountFollowingsWithRelationshipFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getAccountFollowersWithRelationshipFeature =>
      (super.noSuchMethod(
        Invocation.getter(#getAccountFollowersWithRelationshipFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getAccountFollowersWithRelationshipFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get registerAccountFeature => (super.noSuchMethod(
        Invocation.getter(#registerAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#registerAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get registerAccountReasonFeature =>
      (super.noSuchMethod(
        Invocation.getter(#registerAccountReasonFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#registerAccountReasonFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get registerAccountCaptchaFeature =>
      (super.noSuchMethod(
        Invocation.getter(#registerAccountCaptchaFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#registerAccountCaptchaFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get registerAccountFullNameFeature =>
      (super.noSuchMethod(
        Invocation.getter(#registerAccountFullNameFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#registerAccountFullNameFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get registerAccountBioFeature => (super.noSuchMethod(
        Invocation.getter(#registerAccountBioFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#registerAccountBioFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get registerAccountInviteTokenFeature =>
      (super.noSuchMethod(
        Invocation.getter(#registerAccountInviteTokenFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#registerAccountInviteTokenFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i3.IUnifediApiRestService get restService => (super.noSuchMethod(
        Invocation.getter(#restService),
        returnValue: _FakeIUnifediApiRestService_1(
          this,
          Invocation.getter(#restService),
        ),
      ) as _i3.IUnifediApiRestService);

  @override
  bool get isDisposed => (super.noSuchMethod(
        Invocation.getter(#isDisposed),
        returnValue: false,
      ) as bool);

  @override
  _i11.Future<List<_i12.IUnifediApiStatus>> getAccountStatuses({
    required String? accountId,
    required String? tagged,
    required bool? pinned,
    required bool? excludeReplies,
    required bool? excludeReblogs,
    required List<_i13.UnifediApiVisibility>? excludeVisibilities,
    required bool? withMuted,
    required bool? onlyWithMedia,
    required _i14.IUnifediApiPagination? pagination,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountStatuses,
          [],
          {
            #accountId: accountId,
            #tagged: tagged,
            #pinned: pinned,
            #excludeReplies: excludeReplies,
            #excludeReblogs: excludeReblogs,
            #excludeVisibilities: excludeVisibilities,
            #withMuted: withMuted,
            #onlyWithMedia: onlyWithMedia,
            #pagination: pagination,
          },
        ),
        returnValue: _i11.Future<List<_i12.IUnifediApiStatus>>.value(
            <_i12.IUnifediApiStatus>[]),
      ) as _i11.Future<List<_i12.IUnifediApiStatus>>);

  @override
  List<_i13.UnifediApiVisibility>
      calculatePossibleExcludeVisibilitiesValues() => (super.noSuchMethod(
            Invocation.method(
              #calculatePossibleExcludeVisibilitiesValues,
              [],
            ),
            returnValue: <_i13.UnifediApiVisibility>[],
          ) as List<_i13.UnifediApiVisibility>);

  @override
  _i11.Future<List<_i12.IUnifediApiStatus>> getAccountFavouritedStatuses({
    required String? accountId,
    required _i14.IUnifediApiPagination? pagination,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountFavouritedStatuses,
          [],
          {
            #accountId: accountId,
            #pagination: pagination,
          },
        ),
        returnValue: _i11.Future<List<_i12.IUnifediApiStatus>>.value(
            <_i12.IUnifediApiStatus>[]),
      ) as _i11.Future<List<_i12.IUnifediApiStatus>>);

  @override
  _i11.Future<_i4.IUnifediApiAccount> getAccount({
    required String? accountId,
    required bool? withRelationship,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccount,
          [],
          {
            #accountId: accountId,
            #withRelationship: withRelationship,
          },
        ),
        returnValue:
            _i11.Future<_i4.IUnifediApiAccount>.value(_FakeIUnifediApiAccount_2(
          this,
          Invocation.method(
            #getAccount,
            [],
            {
              #accountId: accountId,
              #withRelationship: withRelationship,
            },
          ),
        )),
      ) as _i11.Future<_i4.IUnifediApiAccount>);

  @override
  _i11.Future<List<_i5.IUnifediApiAccountRelationship>>
      getRelationshipWithAccounts({required List<String>? accountIds}) =>
          (super.noSuchMethod(
            Invocation.method(
              #getRelationshipWithAccounts,
              [],
              {#accountIds: accountIds},
            ),
            returnValue:
                _i11.Future<List<_i5.IUnifediApiAccountRelationship>>.value(
                    <_i5.IUnifediApiAccountRelationship>[]),
          ) as _i11.Future<List<_i5.IUnifediApiAccountRelationship>>);

  @override
  _i11.Future<List<_i4.IUnifediApiAccount>> search({
    required String? query,
    required bool? resolve,
    required bool? following,
    required int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [],
          {
            #query: query,
            #resolve: resolve,
            #following: following,
            #limit: limit,
          },
        ),
        returnValue: _i11.Future<List<_i4.IUnifediApiAccount>>.value(
            <_i4.IUnifediApiAccount>[]),
      ) as _i11.Future<List<_i4.IUnifediApiAccount>>);

  @override
  _i11.Future<List<_i15.IUnifediApiList>> getListsWithAccount(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListsWithAccount,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i11.Future<List<_i15.IUnifediApiList>>.value(
            <_i15.IUnifediApiList>[]),
      ) as _i11.Future<List<_i15.IUnifediApiList>>);

  @override
  _i11.Future<List<_i16.IUnifediApiAccountIdentityProof>>
      getAccountIdentifyProofs({required String? accountId}) =>
          (super.noSuchMethod(
            Invocation.method(
              #getAccountIdentifyProofs,
              [],
              {#accountId: accountId},
            ),
            returnValue:
                _i11.Future<List<_i16.IUnifediApiAccountIdentityProof>>.value(
                    <_i16.IUnifediApiAccountIdentityProof>[]),
          ) as _i11.Future<List<_i16.IUnifediApiAccountIdentityProof>>);

  @override
  _i11.Future<_i5.IUnifediApiAccountRelationship> followAccount({
    required String? accountId,
    required bool? notify,
    required bool? reblogs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #followAccount,
          [],
          {
            #accountId: accountId,
            #notify: notify,
            #reblogs: reblogs,
          },
        ),
        returnValue: _i11.Future<_i5.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_3(
          this,
          Invocation.method(
            #followAccount,
            [],
            {
              #accountId: accountId,
              #notify: notify,
              #reblogs: reblogs,
            },
          ),
        )),
      ) as _i11.Future<_i5.IUnifediApiAccountRelationship>);

  @override
  _i11.Future<_i5.IUnifediApiAccountRelationship> unFollowAccount(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #unFollowAccount,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i11.Future<_i5.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_3(
          this,
          Invocation.method(
            #unFollowAccount,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i11.Future<_i5.IUnifediApiAccountRelationship>);

  @override
  _i11.Future<_i5.IUnifediApiAccountRelationship> subscribeAccount(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeAccount,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i11.Future<_i5.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_3(
          this,
          Invocation.method(
            #subscribeAccount,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i11.Future<_i5.IUnifediApiAccountRelationship>);

  @override
  _i11.Future<_i5.IUnifediApiAccountRelationship> unSubscribeAccount(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #unSubscribeAccount,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i11.Future<_i5.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_3(
          this,
          Invocation.method(
            #unSubscribeAccount,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i11.Future<_i5.IUnifediApiAccountRelationship>);

  @override
  _i11.Future<_i5.IUnifediApiAccountRelationship> pinAccount(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #pinAccount,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i11.Future<_i5.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_3(
          this,
          Invocation.method(
            #pinAccount,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i11.Future<_i5.IUnifediApiAccountRelationship>);

  @override
  _i11.Future<_i5.IUnifediApiAccountRelationship> unPinAccount(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #unPinAccount,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i11.Future<_i5.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_3(
          this,
          Invocation.method(
            #unPinAccount,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i11.Future<_i5.IUnifediApiAccountRelationship>);

  @override
  _i11.Future<_i5.IUnifediApiAccountRelationship> muteAccount({
    required String? accountId,
    required bool? notifications,
    required Duration? expireIn,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #muteAccount,
          [],
          {
            #accountId: accountId,
            #notifications: notifications,
            #expireIn: expireIn,
          },
        ),
        returnValue: _i11.Future<_i5.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_3(
          this,
          Invocation.method(
            #muteAccount,
            [],
            {
              #accountId: accountId,
              #notifications: notifications,
              #expireIn: expireIn,
            },
          ),
        )),
      ) as _i11.Future<_i5.IUnifediApiAccountRelationship>);

  @override
  _i11.Future<_i5.IUnifediApiAccountRelationship> unMuteAccount(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #unMuteAccount,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i11.Future<_i5.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_3(
          this,
          Invocation.method(
            #unMuteAccount,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i11.Future<_i5.IUnifediApiAccountRelationship>);

  @override
  _i11.Future<_i5.IUnifediApiAccountRelationship> blockAccount(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #blockAccount,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i11.Future<_i5.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_3(
          this,
          Invocation.method(
            #blockAccount,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i11.Future<_i5.IUnifediApiAccountRelationship>);

  @override
  _i11.Future<_i5.IUnifediApiAccountRelationship> unBlockAccount(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #unBlockAccount,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i11.Future<_i5.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_3(
          this,
          Invocation.method(
            #unBlockAccount,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i11.Future<_i5.IUnifediApiAccountRelationship>);

  @override
  _i11.Future<void> blockDomain({required String? domain}) =>
      (super.noSuchMethod(
        Invocation.method(
          #blockDomain,
          [],
          {#domain: domain},
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> unBlockDomain({required String? domain}) =>
      (super.noSuchMethod(
        Invocation.method(
          #unBlockDomain,
          [],
          {#domain: domain},
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> reportAccount({
    required String? accountId,
    required List<String>? statusIds,
    required String? comment,
    required bool? forward,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportAccount,
          [],
          {
            #accountId: accountId,
            #statusIds: statusIds,
            #comment: comment,
            #forward: forward,
          },
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<List<_i4.IUnifediApiAccount>> getAccountFollowings({
    required String? accountId,
    required bool? withRelationship,
    required _i14.IUnifediApiPagination? pagination,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountFollowings,
          [],
          {
            #accountId: accountId,
            #withRelationship: withRelationship,
            #pagination: pagination,
          },
        ),
        returnValue: _i11.Future<List<_i4.IUnifediApiAccount>>.value(
            <_i4.IUnifediApiAccount>[]),
      ) as _i11.Future<List<_i4.IUnifediApiAccount>>);

  @override
  _i11.Future<List<_i4.IUnifediApiAccount>> getAccountFollowers({
    required String? accountId,
    required bool? withRelationship,
    required _i14.IUnifediApiPagination? pagination,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountFollowers,
          [],
          {
            #accountId: accountId,
            #withRelationship: withRelationship,
            #pagination: pagination,
          },
        ),
        returnValue: _i11.Future<List<_i4.IUnifediApiAccount>>.value(
            <_i4.IUnifediApiAccount>[]),
      ) as _i11.Future<List<_i4.IUnifediApiAccount>>);

  @override
  _i11.Future<_i5.IUnifediApiAccountRelationship> note({
    required String? accountId,
    required String? comment,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #note,
          [],
          {
            #accountId: accountId,
            #comment: comment,
          },
        ),
        returnValue: _i11.Future<_i5.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_3(
          this,
          Invocation.method(
            #note,
            [],
            {
              #accountId: accountId,
              #comment: comment,
            },
          ),
        )),
      ) as _i11.Future<_i5.IUnifediApiAccountRelationship>);

  @override
  _i11.Future<_i6.IUnifediApiRegisterAccountResponse> registerAccount(
          {required _i17.IUnifediApiRegisterAccount? registerAccount}) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerAccount,
          [],
          {#registerAccount: registerAccount},
        ),
        returnValue: _i11.Future<_i6.IUnifediApiRegisterAccountResponse>.value(
            _FakeIUnifediApiRegisterAccountResponse_4(
          this,
          Invocation.method(
            #registerAccount,
            [],
            {#registerAccount: registerAccount},
          ),
        )),
      ) as _i11.Future<_i6.IUnifediApiRegisterAccountResponse>);

  @override
  _i7.FediverseApiFeatureRequirementState checkFeatureState(
          _i2.IUnifediApiFeature? feature) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkFeatureState,
          [feature],
        ),
        returnValue: _FakeFediverseApiFeatureRequirementState_5(
          this,
          Invocation.method(
            #checkFeatureState,
            [feature],
          ),
        ),
      ) as _i7.FediverseApiFeatureRequirementState);

  @override
  _i11.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
}

/// A class which mocks [IUnifediApiWebSocketsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIUnifediApiWebSocketsService extends _i1.Mock
    implements _i18.IUnifediApiWebSocketsService {
  MockIUnifediApiWebSocketsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IUnifediApiFeature get serviceFeature => (super.noSuchMethod(
        Invocation.getter(#serviceFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#serviceFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get listenForPublicEventsFeature =>
      (super.noSuchMethod(
        Invocation.getter(#listenForPublicEventsFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#listenForPublicEventsFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get listenForPublicEventsRemoteOnlyArgFeature =>
      (super.noSuchMethod(
        Invocation.getter(#listenForPublicEventsRemoteOnlyArgFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#listenForPublicEventsRemoteOnlyArgFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get listenForPublicEventsOnlyFromInstanceArgFeature =>
      (super.noSuchMethod(
        Invocation.getter(#listenForPublicEventsOnlyFromInstanceArgFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#listenForPublicEventsOnlyFromInstanceArgFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get listenForAccountConversationEventsFeature =>
      (super.noSuchMethod(
        Invocation.getter(#listenForAccountConversationEventsFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#listenForAccountConversationEventsFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get listenForAllMyAccountEventsFeature =>
      (super.noSuchMethod(
        Invocation.getter(#listenForAllMyAccountEventsFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#listenForAllMyAccountEventsFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get listenForNotificationMyAccountFeature =>
      (super.noSuchMethod(
        Invocation.getter(#listenForNotificationMyAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#listenForNotificationMyAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get listenForChatMyAccountEventsFeature =>
      (super.noSuchMethod(
        Invocation.getter(#listenForChatMyAccountEventsFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#listenForChatMyAccountEventsFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get listenForCustomListEventsFeature =>
      (super.noSuchMethod(
        Invocation.getter(#listenForCustomListEventsFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#listenForCustomListEventsFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get listenForHashtagEventsFeature =>
      (super.noSuchMethod(
        Invocation.getter(#listenForHashtagEventsFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#listenForHashtagEventsFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i3.IUnifediApiRestService get restService => (super.noSuchMethod(
        Invocation.getter(#restService),
        returnValue: _FakeIUnifediApiRestService_1(
          this,
          Invocation.getter(#restService),
        ),
      ) as _i3.IUnifediApiRestService);

  @override
  bool get isDisposed => (super.noSuchMethod(
        Invocation.getter(#isDisposed),
        returnValue: false,
      ) as bool);

  @override
  _i8.IWebSocketsService get webSocketsService => (super.noSuchMethod(
        Invocation.getter(#webSocketsService),
        returnValue: _FakeIWebSocketsService_6(
          this,
          Invocation.getter(#webSocketsService),
        ),
      ) as _i8.IWebSocketsService);

  @override
  _i9.IDisposable listenForPublicEvents({
    required _i8.WebSocketsChannelHandlerType? handlerType,
    required bool? localOnly,
    required bool? remoteOnly,
    required bool? mediaOnly,
    required String? onlyFromInstance,
    required _i19.UnifediApiWebSocketsEventListener? onEvent,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listenForPublicEvents,
          [],
          {
            #handlerType: handlerType,
            #localOnly: localOnly,
            #remoteOnly: remoteOnly,
            #mediaOnly: mediaOnly,
            #onlyFromInstance: onlyFromInstance,
            #onEvent: onEvent,
          },
        ),
        returnValue: _FakeIDisposable_7(
          this,
          Invocation.method(
            #listenForPublicEvents,
            [],
            {
              #handlerType: handlerType,
              #localOnly: localOnly,
              #remoteOnly: remoteOnly,
              #mediaOnly: mediaOnly,
              #onlyFromInstance: onlyFromInstance,
              #onEvent: onEvent,
            },
          ),
        ),
      ) as _i9.IDisposable);

  @override
  _i9.IDisposable listenForAllConversationEvents({
    required _i8.WebSocketsChannelHandlerType? handlerType,
    required _i19.UnifediApiWebSocketsEventListener? onEvent,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listenForAllConversationEvents,
          [],
          {
            #handlerType: handlerType,
            #onEvent: onEvent,
          },
        ),
        returnValue: _FakeIDisposable_7(
          this,
          Invocation.method(
            #listenForAllConversationEvents,
            [],
            {
              #handlerType: handlerType,
              #onEvent: onEvent,
            },
          ),
        ),
      ) as _i9.IDisposable);

  @override
  _i9.IDisposable listenForAccountConversationEvents({
    required _i8.WebSocketsChannelHandlerType? handlerType,
    required String? accountId,
    required _i19.UnifediApiWebSocketsEventListener? onEvent,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listenForAccountConversationEvents,
          [],
          {
            #handlerType: handlerType,
            #accountId: accountId,
            #onEvent: onEvent,
          },
        ),
        returnValue: _FakeIDisposable_7(
          this,
          Invocation.method(
            #listenForAccountConversationEvents,
            [],
            {
              #handlerType: handlerType,
              #accountId: accountId,
              #onEvent: onEvent,
            },
          ),
        ),
      ) as _i9.IDisposable);

  @override
  _i9.IDisposable listenForAllMyAccountEvents({
    required _i8.WebSocketsChannelHandlerType? handlerType,
    required _i19.UnifediApiWebSocketsEventListener? onEvent,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listenForAllMyAccountEvents,
          [],
          {
            #handlerType: handlerType,
            #onEvent: onEvent,
          },
        ),
        returnValue: _FakeIDisposable_7(
          this,
          Invocation.method(
            #listenForAllMyAccountEvents,
            [],
            {
              #handlerType: handlerType,
              #onEvent: onEvent,
            },
          ),
        ),
      ) as _i9.IDisposable);

  @override
  _i9.IDisposable listenForNotificationMyAccountEvents({
    required _i8.WebSocketsChannelHandlerType? handlerType,
    required _i19.UnifediApiWebSocketsEventListener? onEvent,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listenForNotificationMyAccountEvents,
          [],
          {
            #handlerType: handlerType,
            #onEvent: onEvent,
          },
        ),
        returnValue: _FakeIDisposable_7(
          this,
          Invocation.method(
            #listenForNotificationMyAccountEvents,
            [],
            {
              #handlerType: handlerType,
              #onEvent: onEvent,
            },
          ),
        ),
      ) as _i9.IDisposable);

  @override
  _i9.IDisposable listenForChatMyAccountEvents({
    required _i8.WebSocketsChannelHandlerType? handlerType,
    required _i19.UnifediApiWebSocketsEventListener? onEvent,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listenForChatMyAccountEvents,
          [],
          {
            #handlerType: handlerType,
            #onEvent: onEvent,
          },
        ),
        returnValue: _FakeIDisposable_7(
          this,
          Invocation.method(
            #listenForChatMyAccountEvents,
            [],
            {
              #handlerType: handlerType,
              #onEvent: onEvent,
            },
          ),
        ),
      ) as _i9.IDisposable);

  @override
  _i9.IDisposable listenForCustomListEvents({
    required _i8.WebSocketsChannelHandlerType? handlerType,
    required String? listId,
    required _i19.UnifediApiWebSocketsEventListener? onEvent,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listenForCustomListEvents,
          [],
          {
            #handlerType: handlerType,
            #listId: listId,
            #onEvent: onEvent,
          },
        ),
        returnValue: _FakeIDisposable_7(
          this,
          Invocation.method(
            #listenForCustomListEvents,
            [],
            {
              #handlerType: handlerType,
              #listId: listId,
              #onEvent: onEvent,
            },
          ),
        ),
      ) as _i9.IDisposable);

  @override
  _i9.IDisposable listenForHashtagEvents({
    required _i8.WebSocketsChannelHandlerType? handlerType,
    required bool? localOnly,
    required String? tag,
    required _i19.UnifediApiWebSocketsEventListener? onEvent,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listenForHashtagEvents,
          [],
          {
            #handlerType: handlerType,
            #localOnly: localOnly,
            #tag: tag,
            #onEvent: onEvent,
          },
        ),
        returnValue: _FakeIDisposable_7(
          this,
          Invocation.method(
            #listenForHashtagEvents,
            [],
            {
              #handlerType: handlerType,
              #localOnly: localOnly,
              #tag: tag,
              #onEvent: onEvent,
            },
          ),
        ),
      ) as _i9.IDisposable);

  @override
  _i7.FediverseApiFeatureRequirementState checkFeatureState(
          _i2.IUnifediApiFeature? feature) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkFeatureState,
          [feature],
        ),
        returnValue: _FakeFediverseApiFeatureRequirementState_5(
          this,
          Invocation.method(
            #checkFeatureState,
            [feature],
          ),
        ),
      ) as _i7.FediverseApiFeatureRequirementState);

  @override
  _i11.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
}
