// Mocks generated by Mockito 5.4.4 from annotations
// in fedi_app/test/app/chat/message/chat_message_bloc_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;

import 'package:connectivity_plus/connectivity_plus.dart' as _i27;
import 'package:easy_dispose/easy_dispose.dart' as _i22;
import 'package:fedi_app/app/account/account_model.dart' as _i11;
import 'package:fedi_app/app/account/my/my_account_bloc.dart' as _i20;
import 'package:fedi_app/app/account/my/my_account_model.dart' as _i21;
import 'package:fedi_app/app/chat/message/chat_message_model.dart' as _i25;
import 'package:fedi_app/app/instance/location/instance_location_model.dart'
    as _i23;
import 'package:fedi_app/app/status/status_model.dart' as _i24;
import 'package:fedi_app/connection/connection_service.dart' as _i26;
import 'package:fediverse_api/fediverse_api.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:unifedi_api/src/api/account/identity_proof/unifedi_api_account_identity_proof_model.dart'
    as _i18;
import 'package:unifedi_api/src/api/account/register/response/unifedi_api_register_account_response_model.dart'
    as _i9;
import 'package:unifedi_api/src/api/account/register/unifedi_api_register_account_model.dart'
    as _i19;
import 'package:unifedi_api/src/api/account/relationship/unifedi_api_account_relationship_model.dart'
    as _i8;
import 'package:unifedi_api/src/api/account/unifedi_api_account_model.dart'
    as _i7;
import 'package:unifedi_api/src/api/chat/message/post/unifedi_api_post_chat_message_model.dart'
    as _i14;
import 'package:unifedi_api/src/api/chat/message/unifedi_api_chat_message_model.dart'
    as _i5;
import 'package:unifedi_api/src/api/chat/unifedi_api_chat_model.dart' as _i4;
import 'package:unifedi_api/src/api/feature/unifedi_api_feature_model.dart'
    as _i2;
import 'package:unifedi_api/src/api/list/unifedi_api_list_model.dart' as _i17;
import 'package:unifedi_api/src/api/pagination/unifedi_api_pagination_model.dart'
    as _i13;
import 'package:unifedi_api/src/api/rest/unifedi_api_rest_service.dart' as _i3;
import 'package:unifedi_api/src/api/status/unifedi_api_status_model.dart'
    as _i15;
import 'package:unifedi_api/src/api/visibility/unifedi_api_visibility_sealed.dart'
    as _i16;
import 'package:unifedi_api/unifedi_api.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIUnifediApiFeature_0 extends _i1.SmartFake
    implements _i2.IUnifediApiFeature {
  _FakeIUnifediApiFeature_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIUnifediApiRestService_1 extends _i1.SmartFake
    implements _i3.IUnifediApiRestService {
  _FakeIUnifediApiRestService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIUnifediApiChat_2 extends _i1.SmartFake
    implements _i4.IUnifediApiChat {
  _FakeIUnifediApiChat_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIUnifediApiChatMessage_3 extends _i1.SmartFake
    implements _i5.IUnifediApiChatMessage {
  _FakeIUnifediApiChatMessage_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFediverseApiFeatureRequirementState_4 extends _i1.SmartFake
    implements _i6.FediverseApiFeatureRequirementState {
  _FakeFediverseApiFeatureRequirementState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIUnifediApiAccount_5 extends _i1.SmartFake
    implements _i7.IUnifediApiAccount {
  _FakeIUnifediApiAccount_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIUnifediApiAccountRelationship_6 extends _i1.SmartFake
    implements _i8.IUnifediApiAccountRelationship {
  _FakeIUnifediApiAccountRelationship_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIUnifediApiRegisterAccountResponse_7 extends _i1.SmartFake
    implements _i9.IUnifediApiRegisterAccountResponse {
  _FakeIUnifediApiRegisterAccountResponse_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUnifediApiAccess_8 extends _i1.SmartFake
    implements _i10.UnifediApiAccess {
  _FakeUnifediApiAccess_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIAccount_9 extends _i1.SmartFake implements _i11.IAccount {
  _FakeIAccount_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IUnifediApiChatService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIUnifediApiChatService extends _i1.Mock
    implements _i10.IUnifediApiChatService {
  MockIUnifediApiChatService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IUnifediApiFeature get getChatsFeature => (super.noSuchMethod(
        Invocation.getter(#getChatsFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getChatsFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getChatMessagesFeature => (super.noSuchMethod(
        Invocation.getter(#getChatMessagesFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getChatMessagesFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get markChatAsReadFeature => (super.noSuchMethod(
        Invocation.getter(#markChatAsReadFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#markChatAsReadFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getChatFeature => (super.noSuchMethod(
        Invocation.getter(#getChatFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getChatFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getOrCreateChatByAccountIdFeature =>
      (super.noSuchMethod(
        Invocation.getter(#getOrCreateChatByAccountIdFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getOrCreateChatByAccountIdFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get sendMessageFeature => (super.noSuchMethod(
        Invocation.getter(#sendMessageFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#sendMessageFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get deleteChatMessageFeature => (super.noSuchMethod(
        Invocation.getter(#deleteChatMessageFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#deleteChatMessageFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i3.IUnifediApiRestService get restService => (super.noSuchMethod(
        Invocation.getter(#restService),
        returnValue: _FakeIUnifediApiRestService_1(
          this,
          Invocation.getter(#restService),
        ),
      ) as _i3.IUnifediApiRestService);

  @override
  bool get isDisposed => (super.noSuchMethod(
        Invocation.getter(#isDisposed),
        returnValue: false,
      ) as bool);

  @override
  _i12.Future<List<_i4.IUnifediApiChat>> getChats(
          {required _i13.IUnifediApiPagination? pagination}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChats,
          [],
          {#pagination: pagination},
        ),
        returnValue: _i12.Future<List<_i4.IUnifediApiChat>>.value(
            <_i4.IUnifediApiChat>[]),
      ) as _i12.Future<List<_i4.IUnifediApiChat>>);

  @override
  _i12.Future<List<_i5.IUnifediApiChatMessage>> getChatMessages({
    required String? chatId,
    required _i13.IUnifediApiPagination? pagination,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChatMessages,
          [],
          {
            #chatId: chatId,
            #pagination: pagination,
          },
        ),
        returnValue: _i12.Future<List<_i5.IUnifediApiChatMessage>>.value(
            <_i5.IUnifediApiChatMessage>[]),
      ) as _i12.Future<List<_i5.IUnifediApiChatMessage>>);

  @override
  _i12.Future<_i4.IUnifediApiChat> markChatAsRead({
    required String? chatId,
    required String? lastReadChatMessageId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markChatAsRead,
          [],
          {
            #chatId: chatId,
            #lastReadChatMessageId: lastReadChatMessageId,
          },
        ),
        returnValue:
            _i12.Future<_i4.IUnifediApiChat>.value(_FakeIUnifediApiChat_2(
          this,
          Invocation.method(
            #markChatAsRead,
            [],
            {
              #chatId: chatId,
              #lastReadChatMessageId: lastReadChatMessageId,
            },
          ),
        )),
      ) as _i12.Future<_i4.IUnifediApiChat>);

  @override
  _i12.Future<_i4.IUnifediApiChat> getChat({required String? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChat,
          [],
          {#id: id},
        ),
        returnValue:
            _i12.Future<_i4.IUnifediApiChat>.value(_FakeIUnifediApiChat_2(
          this,
          Invocation.method(
            #getChat,
            [],
            {#id: id},
          ),
        )),
      ) as _i12.Future<_i4.IUnifediApiChat>);

  @override
  _i12.Future<_i4.IUnifediApiChat> getOrCreateChatByAccountId(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrCreateChatByAccountId,
          [],
          {#accountId: accountId},
        ),
        returnValue:
            _i12.Future<_i4.IUnifediApiChat>.value(_FakeIUnifediApiChat_2(
          this,
          Invocation.method(
            #getOrCreateChatByAccountId,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i12.Future<_i4.IUnifediApiChat>);

  @override
  _i12.Future<_i5.IUnifediApiChatMessage> sendMessage({
    required String? idempotencyKey,
    required String? chatId,
    required _i14.IUnifediApiPostChatMessage? postChatMessage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [],
          {
            #idempotencyKey: idempotencyKey,
            #chatId: chatId,
            #postChatMessage: postChatMessage,
          },
        ),
        returnValue: _i12.Future<_i5.IUnifediApiChatMessage>.value(
            _FakeIUnifediApiChatMessage_3(
          this,
          Invocation.method(
            #sendMessage,
            [],
            {
              #idempotencyKey: idempotencyKey,
              #chatId: chatId,
              #postChatMessage: postChatMessage,
            },
          ),
        )),
      ) as _i12.Future<_i5.IUnifediApiChatMessage>);

  @override
  _i12.Future<void> deleteChatMessage({
    required String? chatMessageId,
    required String? chatId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteChatMessage,
          [],
          {
            #chatMessageId: chatMessageId,
            #chatId: chatId,
          },
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i6.FediverseApiFeatureRequirementState checkFeatureState(
          _i2.IUnifediApiFeature? feature) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkFeatureState,
          [feature],
        ),
        returnValue: _FakeFediverseApiFeatureRequirementState_4(
          this,
          Invocation.method(
            #checkFeatureState,
            [feature],
          ),
        ),
      ) as _i6.FediverseApiFeatureRequirementState);

  @override
  _i12.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);
}

/// A class which mocks [IUnifediApiAccountService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIUnifediApiAccountService extends _i1.Mock
    implements _i10.IUnifediApiAccountService {
  MockIUnifediApiAccountService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IUnifediApiFeature get getAccountStatusesFeature => (super.noSuchMethod(
        Invocation.getter(#getAccountStatusesFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getAccountStatusesFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getAccountStatusesWithMutedFeature =>
      (super.noSuchMethod(
        Invocation.getter(#getAccountStatusesWithMutedFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getAccountStatusesWithMutedFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getAccountStatusesExcludeVisibilitiesFeature =>
      (super.noSuchMethod(
        Invocation.getter(#getAccountStatusesExcludeVisibilitiesFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getAccountStatusesExcludeVisibilitiesFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getAccountStatusesPaginationMinIdFeature =>
      (super.noSuchMethod(
        Invocation.getter(#getAccountStatusesPaginationMinIdFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getAccountStatusesPaginationMinIdFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getAccountStatusesExcludeReblogsFeature =>
      (super.noSuchMethod(
        Invocation.getter(#getAccountStatusesExcludeReblogsFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getAccountStatusesExcludeReblogsFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getAccountStatusesTaggedFeature =>
      (super.noSuchMethod(
        Invocation.getter(#getAccountStatusesTaggedFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getAccountStatusesTaggedFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getAccountFavouritedStatusesFeature =>
      (super.noSuchMethod(
        Invocation.getter(#getAccountFavouritedStatusesFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getAccountFavouritedStatusesFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getAccountFeature => (super.noSuchMethod(
        Invocation.getter(#getAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getAccountWithRelationshipFeature =>
      (super.noSuchMethod(
        Invocation.getter(#getAccountWithRelationshipFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getAccountWithRelationshipFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getRelationshipWithAccountsFeature =>
      (super.noSuchMethod(
        Invocation.getter(#getRelationshipWithAccountsFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getRelationshipWithAccountsFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get searchFeature => (super.noSuchMethod(
        Invocation.getter(#searchFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#searchFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getListsWithAccountFeature => (super.noSuchMethod(
        Invocation.getter(#getListsWithAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getListsWithAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getAccountIdentifyProofsFeature =>
      (super.noSuchMethod(
        Invocation.getter(#getAccountIdentifyProofsFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getAccountIdentifyProofsFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get followAccountFeature => (super.noSuchMethod(
        Invocation.getter(#followAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#followAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get followAccountNotifyFeature => (super.noSuchMethod(
        Invocation.getter(#followAccountNotifyFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#followAccountNotifyFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get unFollowAccountFeature => (super.noSuchMethod(
        Invocation.getter(#unFollowAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#unFollowAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get pinAccountFeature => (super.noSuchMethod(
        Invocation.getter(#pinAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#pinAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get unPinAccountFeature => (super.noSuchMethod(
        Invocation.getter(#unPinAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#unPinAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get muteAccountFeature => (super.noSuchMethod(
        Invocation.getter(#muteAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#muteAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get unMuteAccountFeature => (super.noSuchMethod(
        Invocation.getter(#unMuteAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#unMuteAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get subscribeAccountFeature => (super.noSuchMethod(
        Invocation.getter(#subscribeAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#subscribeAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get unSubscribeAccountFeature => (super.noSuchMethod(
        Invocation.getter(#unSubscribeAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#unSubscribeAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get blockAccountFeature => (super.noSuchMethod(
        Invocation.getter(#blockAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#blockAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get unBlockAccountFeature => (super.noSuchMethod(
        Invocation.getter(#unBlockAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#unBlockAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get blockDomainFeature => (super.noSuchMethod(
        Invocation.getter(#blockDomainFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#blockDomainFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get unBlockDomainFeature => (super.noSuchMethod(
        Invocation.getter(#unBlockDomainFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#unBlockDomainFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get noteFeature => (super.noSuchMethod(
        Invocation.getter(#noteFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#noteFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get reportAccountFeature => (super.noSuchMethod(
        Invocation.getter(#reportAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#reportAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get reportAccountForwardFeature => (super.noSuchMethod(
        Invocation.getter(#reportAccountForwardFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#reportAccountForwardFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getAccountFollowingsFeature => (super.noSuchMethod(
        Invocation.getter(#getAccountFollowingsFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getAccountFollowingsFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getAccountFollowersFeature => (super.noSuchMethod(
        Invocation.getter(#getAccountFollowersFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getAccountFollowersFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getAccountFollowingsWithRelationshipFeature =>
      (super.noSuchMethod(
        Invocation.getter(#getAccountFollowingsWithRelationshipFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getAccountFollowingsWithRelationshipFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getAccountFollowersWithRelationshipFeature =>
      (super.noSuchMethod(
        Invocation.getter(#getAccountFollowersWithRelationshipFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getAccountFollowersWithRelationshipFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get registerAccountFeature => (super.noSuchMethod(
        Invocation.getter(#registerAccountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#registerAccountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get registerAccountReasonFeature =>
      (super.noSuchMethod(
        Invocation.getter(#registerAccountReasonFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#registerAccountReasonFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get registerAccountCaptchaFeature =>
      (super.noSuchMethod(
        Invocation.getter(#registerAccountCaptchaFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#registerAccountCaptchaFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get registerAccountFullNameFeature =>
      (super.noSuchMethod(
        Invocation.getter(#registerAccountFullNameFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#registerAccountFullNameFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get registerAccountBioFeature => (super.noSuchMethod(
        Invocation.getter(#registerAccountBioFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#registerAccountBioFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get registerAccountInviteTokenFeature =>
      (super.noSuchMethod(
        Invocation.getter(#registerAccountInviteTokenFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#registerAccountInviteTokenFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i3.IUnifediApiRestService get restService => (super.noSuchMethod(
        Invocation.getter(#restService),
        returnValue: _FakeIUnifediApiRestService_1(
          this,
          Invocation.getter(#restService),
        ),
      ) as _i3.IUnifediApiRestService);

  @override
  bool get isDisposed => (super.noSuchMethod(
        Invocation.getter(#isDisposed),
        returnValue: false,
      ) as bool);

  @override
  _i12.Future<List<_i15.IUnifediApiStatus>> getAccountStatuses({
    required String? accountId,
    required String? tagged,
    required bool? pinned,
    required bool? excludeReplies,
    required bool? excludeReblogs,
    required List<_i16.UnifediApiVisibility>? excludeVisibilities,
    required bool? withMuted,
    required bool? onlyWithMedia,
    required _i13.IUnifediApiPagination? pagination,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountStatuses,
          [],
          {
            #accountId: accountId,
            #tagged: tagged,
            #pinned: pinned,
            #excludeReplies: excludeReplies,
            #excludeReblogs: excludeReblogs,
            #excludeVisibilities: excludeVisibilities,
            #withMuted: withMuted,
            #onlyWithMedia: onlyWithMedia,
            #pagination: pagination,
          },
        ),
        returnValue: _i12.Future<List<_i15.IUnifediApiStatus>>.value(
            <_i15.IUnifediApiStatus>[]),
      ) as _i12.Future<List<_i15.IUnifediApiStatus>>);

  @override
  List<_i16.UnifediApiVisibility>
      calculatePossibleExcludeVisibilitiesValues() => (super.noSuchMethod(
            Invocation.method(
              #calculatePossibleExcludeVisibilitiesValues,
              [],
            ),
            returnValue: <_i16.UnifediApiVisibility>[],
          ) as List<_i16.UnifediApiVisibility>);

  @override
  _i12.Future<List<_i15.IUnifediApiStatus>> getAccountFavouritedStatuses({
    required String? accountId,
    required _i13.IUnifediApiPagination? pagination,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountFavouritedStatuses,
          [],
          {
            #accountId: accountId,
            #pagination: pagination,
          },
        ),
        returnValue: _i12.Future<List<_i15.IUnifediApiStatus>>.value(
            <_i15.IUnifediApiStatus>[]),
      ) as _i12.Future<List<_i15.IUnifediApiStatus>>);

  @override
  _i12.Future<_i7.IUnifediApiAccount> getAccount({
    required String? accountId,
    required bool? withRelationship,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccount,
          [],
          {
            #accountId: accountId,
            #withRelationship: withRelationship,
          },
        ),
        returnValue:
            _i12.Future<_i7.IUnifediApiAccount>.value(_FakeIUnifediApiAccount_5(
          this,
          Invocation.method(
            #getAccount,
            [],
            {
              #accountId: accountId,
              #withRelationship: withRelationship,
            },
          ),
        )),
      ) as _i12.Future<_i7.IUnifediApiAccount>);

  @override
  _i12.Future<List<_i8.IUnifediApiAccountRelationship>>
      getRelationshipWithAccounts({required List<String>? accountIds}) =>
          (super.noSuchMethod(
            Invocation.method(
              #getRelationshipWithAccounts,
              [],
              {#accountIds: accountIds},
            ),
            returnValue:
                _i12.Future<List<_i8.IUnifediApiAccountRelationship>>.value(
                    <_i8.IUnifediApiAccountRelationship>[]),
          ) as _i12.Future<List<_i8.IUnifediApiAccountRelationship>>);

  @override
  _i12.Future<List<_i7.IUnifediApiAccount>> search({
    required String? query,
    required bool? resolve,
    required bool? following,
    required int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [],
          {
            #query: query,
            #resolve: resolve,
            #following: following,
            #limit: limit,
          },
        ),
        returnValue: _i12.Future<List<_i7.IUnifediApiAccount>>.value(
            <_i7.IUnifediApiAccount>[]),
      ) as _i12.Future<List<_i7.IUnifediApiAccount>>);

  @override
  _i12.Future<List<_i17.IUnifediApiList>> getListsWithAccount(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListsWithAccount,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i12.Future<List<_i17.IUnifediApiList>>.value(
            <_i17.IUnifediApiList>[]),
      ) as _i12.Future<List<_i17.IUnifediApiList>>);

  @override
  _i12.Future<List<_i18.IUnifediApiAccountIdentityProof>>
      getAccountIdentifyProofs({required String? accountId}) =>
          (super.noSuchMethod(
            Invocation.method(
              #getAccountIdentifyProofs,
              [],
              {#accountId: accountId},
            ),
            returnValue:
                _i12.Future<List<_i18.IUnifediApiAccountIdentityProof>>.value(
                    <_i18.IUnifediApiAccountIdentityProof>[]),
          ) as _i12.Future<List<_i18.IUnifediApiAccountIdentityProof>>);

  @override
  _i12.Future<_i8.IUnifediApiAccountRelationship> followAccount({
    required String? accountId,
    required bool? notify,
    required bool? reblogs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #followAccount,
          [],
          {
            #accountId: accountId,
            #notify: notify,
            #reblogs: reblogs,
          },
        ),
        returnValue: _i12.Future<_i8.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_6(
          this,
          Invocation.method(
            #followAccount,
            [],
            {
              #accountId: accountId,
              #notify: notify,
              #reblogs: reblogs,
            },
          ),
        )),
      ) as _i12.Future<_i8.IUnifediApiAccountRelationship>);

  @override
  _i12.Future<_i8.IUnifediApiAccountRelationship> unFollowAccount(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #unFollowAccount,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i12.Future<_i8.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_6(
          this,
          Invocation.method(
            #unFollowAccount,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i12.Future<_i8.IUnifediApiAccountRelationship>);

  @override
  _i12.Future<_i8.IUnifediApiAccountRelationship> subscribeAccount(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeAccount,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i12.Future<_i8.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_6(
          this,
          Invocation.method(
            #subscribeAccount,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i12.Future<_i8.IUnifediApiAccountRelationship>);

  @override
  _i12.Future<_i8.IUnifediApiAccountRelationship> unSubscribeAccount(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #unSubscribeAccount,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i12.Future<_i8.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_6(
          this,
          Invocation.method(
            #unSubscribeAccount,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i12.Future<_i8.IUnifediApiAccountRelationship>);

  @override
  _i12.Future<_i8.IUnifediApiAccountRelationship> pinAccount(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #pinAccount,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i12.Future<_i8.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_6(
          this,
          Invocation.method(
            #pinAccount,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i12.Future<_i8.IUnifediApiAccountRelationship>);

  @override
  _i12.Future<_i8.IUnifediApiAccountRelationship> unPinAccount(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #unPinAccount,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i12.Future<_i8.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_6(
          this,
          Invocation.method(
            #unPinAccount,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i12.Future<_i8.IUnifediApiAccountRelationship>);

  @override
  _i12.Future<_i8.IUnifediApiAccountRelationship> muteAccount({
    required String? accountId,
    required bool? notifications,
    required Duration? expireIn,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #muteAccount,
          [],
          {
            #accountId: accountId,
            #notifications: notifications,
            #expireIn: expireIn,
          },
        ),
        returnValue: _i12.Future<_i8.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_6(
          this,
          Invocation.method(
            #muteAccount,
            [],
            {
              #accountId: accountId,
              #notifications: notifications,
              #expireIn: expireIn,
            },
          ),
        )),
      ) as _i12.Future<_i8.IUnifediApiAccountRelationship>);

  @override
  _i12.Future<_i8.IUnifediApiAccountRelationship> unMuteAccount(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #unMuteAccount,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i12.Future<_i8.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_6(
          this,
          Invocation.method(
            #unMuteAccount,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i12.Future<_i8.IUnifediApiAccountRelationship>);

  @override
  _i12.Future<_i8.IUnifediApiAccountRelationship> blockAccount(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #blockAccount,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i12.Future<_i8.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_6(
          this,
          Invocation.method(
            #blockAccount,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i12.Future<_i8.IUnifediApiAccountRelationship>);

  @override
  _i12.Future<_i8.IUnifediApiAccountRelationship> unBlockAccount(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #unBlockAccount,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i12.Future<_i8.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_6(
          this,
          Invocation.method(
            #unBlockAccount,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i12.Future<_i8.IUnifediApiAccountRelationship>);

  @override
  _i12.Future<void> blockDomain({required String? domain}) =>
      (super.noSuchMethod(
        Invocation.method(
          #blockDomain,
          [],
          {#domain: domain},
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> unBlockDomain({required String? domain}) =>
      (super.noSuchMethod(
        Invocation.method(
          #unBlockDomain,
          [],
          {#domain: domain},
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> reportAccount({
    required String? accountId,
    required List<String>? statusIds,
    required String? comment,
    required bool? forward,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportAccount,
          [],
          {
            #accountId: accountId,
            #statusIds: statusIds,
            #comment: comment,
            #forward: forward,
          },
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<List<_i7.IUnifediApiAccount>> getAccountFollowings({
    required String? accountId,
    required bool? withRelationship,
    required _i13.IUnifediApiPagination? pagination,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountFollowings,
          [],
          {
            #accountId: accountId,
            #withRelationship: withRelationship,
            #pagination: pagination,
          },
        ),
        returnValue: _i12.Future<List<_i7.IUnifediApiAccount>>.value(
            <_i7.IUnifediApiAccount>[]),
      ) as _i12.Future<List<_i7.IUnifediApiAccount>>);

  @override
  _i12.Future<List<_i7.IUnifediApiAccount>> getAccountFollowers({
    required String? accountId,
    required bool? withRelationship,
    required _i13.IUnifediApiPagination? pagination,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountFollowers,
          [],
          {
            #accountId: accountId,
            #withRelationship: withRelationship,
            #pagination: pagination,
          },
        ),
        returnValue: _i12.Future<List<_i7.IUnifediApiAccount>>.value(
            <_i7.IUnifediApiAccount>[]),
      ) as _i12.Future<List<_i7.IUnifediApiAccount>>);

  @override
  _i12.Future<_i8.IUnifediApiAccountRelationship> note({
    required String? accountId,
    required String? comment,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #note,
          [],
          {
            #accountId: accountId,
            #comment: comment,
          },
        ),
        returnValue: _i12.Future<_i8.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_6(
          this,
          Invocation.method(
            #note,
            [],
            {
              #accountId: accountId,
              #comment: comment,
            },
          ),
        )),
      ) as _i12.Future<_i8.IUnifediApiAccountRelationship>);

  @override
  _i12.Future<_i9.IUnifediApiRegisterAccountResponse> registerAccount(
          {required _i19.IUnifediApiRegisterAccount? registerAccount}) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerAccount,
          [],
          {#registerAccount: registerAccount},
        ),
        returnValue: _i12.Future<_i9.IUnifediApiRegisterAccountResponse>.value(
            _FakeIUnifediApiRegisterAccountResponse_7(
          this,
          Invocation.method(
            #registerAccount,
            [],
            {#registerAccount: registerAccount},
          ),
        )),
      ) as _i12.Future<_i9.IUnifediApiRegisterAccountResponse>);

  @override
  _i6.FediverseApiFeatureRequirementState checkFeatureState(
          _i2.IUnifediApiFeature? feature) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkFeatureState,
          [feature],
        ),
        returnValue: _FakeFediverseApiFeatureRequirementState_4(
          this,
          Invocation.method(
            #checkFeatureState,
            [feature],
          ),
        ),
      ) as _i6.FediverseApiFeatureRequirementState);

  @override
  _i12.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);
}

/// A class which mocks [IMyAccountBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockIMyAccountBloc extends _i1.Mock implements _i20.IMyAccountBloc {
  MockIMyAccountBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Stream<_i21.IMyAccount?> get myAccountStream => (super.noSuchMethod(
        Invocation.getter(#myAccountStream),
        returnValue: _i12.Stream<_i21.IMyAccount?>.empty(),
      ) as _i12.Stream<_i21.IMyAccount?>);

  @override
  _i10.UnifediApiAccess get instance => (super.noSuchMethod(
        Invocation.getter(#instance),
        returnValue: _FakeUnifediApiAccess_8(
          this,
          Invocation.getter(#instance),
        ),
      ) as _i10.UnifediApiAccess);

  @override
  bool get isLocalCacheExist => (super.noSuchMethod(
        Invocation.getter(#isLocalCacheExist),
        returnValue: false,
      ) as bool);

  @override
  bool get isEndorsementSupported => (super.noSuchMethod(
        Invocation.getter(#isEndorsementSupported),
        returnValue: false,
      ) as bool);

  @override
  bool get isSubscribeToAccountFeatureSupported => (super.noSuchMethod(
        Invocation.getter(#isSubscribeToAccountFeatureSupported),
        returnValue: false,
      ) as bool);

  @override
  _i11.IAccount get account => (super.noSuchMethod(
        Invocation.getter(#account),
        returnValue: _FakeIAccount_9(
          this,
          Invocation.getter(#account),
        ),
      ) as _i11.IAccount);

  @override
  _i12.Stream<_i11.IAccount> get accountStream => (super.noSuchMethod(
        Invocation.getter(#accountStream),
        returnValue: _i12.Stream<_i11.IAccount>.empty(),
      ) as _i12.Stream<_i11.IAccount>);

  @override
  _i22.DisposeOrder get disposeOrder => (super.noSuchMethod(
        Invocation.getter(#disposeOrder),
        returnValue: _i22.DisposeOrder.lifo,
      ) as _i22.DisposeOrder);

  @override
  bool get catchExceptions => (super.noSuchMethod(
        Invocation.getter(#catchExceptions),
        returnValue: false,
      ) as bool);

  @override
  List<_i22.IDisposable> get disposables => (super.noSuchMethod(
        Invocation.getter(#disposables),
        returnValue: <_i22.IDisposable>[],
      ) as List<_i22.IDisposable>);

  @override
  bool get isDisposed => (super.noSuchMethod(
        Invocation.getter(#isDisposed),
        returnValue: false,
      ) as bool);

  @override
  set isDisposed(bool? _isDisposed) => super.noSuchMethod(
        Invocation.setter(
          #isDisposed,
          _isDisposed,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i23.InstanceLocation get instanceLocation => (super.noSuchMethod(
        Invocation.getter(#instanceLocation),
        returnValue: _i23.InstanceLocation.local,
      ) as _i23.InstanceLocation);

  @override
  bool checkAccountIsMe(_i11.IAccount? account) => (super.noSuchMethod(
        Invocation.method(
          #checkAccountIsMe,
          [account],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool checkIsStatusFromMe(_i24.IStatus? status) => (super.noSuchMethod(
        Invocation.method(
          #checkIsStatusFromMe,
          [status],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i12.Future<void> updateMyAccountByMyUnifediApiAccount(
          _i10.IUnifediApiMyAccount? unifediApiMyAccount) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMyAccountByMyUnifediApiAccount,
          [unifediApiMyAccount],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> updateMyAccountByMyAccount(_i21.IMyAccount? myAccount) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMyAccountByMyAccount,
          [myAccount],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> decreaseFollowingRequestCount() => (super.noSuchMethod(
        Invocation.method(
          #decreaseFollowingRequestCount,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  bool checkIsChatMessageFromMe(_i25.IChatMessage? chatMessage) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkIsChatMessageFromMe,
          [chatMessage],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i12.Future<_i8.IUnifediApiAccountRelationship> toggleFollow() =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleFollow,
          [],
        ),
        returnValue: _i12.Future<_i8.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_6(
          this,
          Invocation.method(
            #toggleFollow,
            [],
          ),
        )),
      ) as _i12.Future<_i8.IUnifediApiAccountRelationship>);

  @override
  _i12.Future<_i8.IUnifediApiAccountRelationship> toggleMute() =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleMute,
          [],
        ),
        returnValue: _i12.Future<_i8.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_6(
          this,
          Invocation.method(
            #toggleMute,
            [],
          ),
        )),
      ) as _i12.Future<_i8.IUnifediApiAccountRelationship>);

  @override
  _i12.Future<_i8.IUnifediApiAccountRelationship> mute({
    required bool? notifications,
    required Duration? duration,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #mute,
          [],
          {
            #notifications: notifications,
            #duration: duration,
          },
        ),
        returnValue: _i12.Future<_i8.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_6(
          this,
          Invocation.method(
            #mute,
            [],
            {
              #notifications: notifications,
              #duration: duration,
            },
          ),
        )),
      ) as _i12.Future<_i8.IUnifediApiAccountRelationship>);

  @override
  _i12.Future<_i8.IUnifediApiAccountRelationship> unMute() =>
      (super.noSuchMethod(
        Invocation.method(
          #unMute,
          [],
        ),
        returnValue: _i12.Future<_i8.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_6(
          this,
          Invocation.method(
            #unMute,
            [],
          ),
        )),
      ) as _i12.Future<_i8.IUnifediApiAccountRelationship>);

  @override
  _i12.Future<_i8.IUnifediApiAccountRelationship> subscribe() =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [],
        ),
        returnValue: _i12.Future<_i8.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_6(
          this,
          Invocation.method(
            #subscribe,
            [],
          ),
        )),
      ) as _i12.Future<_i8.IUnifediApiAccountRelationship>);

  @override
  _i12.Future<_i8.IUnifediApiAccountRelationship> unSubscribe() =>
      (super.noSuchMethod(
        Invocation.method(
          #unSubscribe,
          [],
        ),
        returnValue: _i12.Future<_i8.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_6(
          this,
          Invocation.method(
            #unSubscribe,
            [],
          ),
        )),
      ) as _i12.Future<_i8.IUnifediApiAccountRelationship>);

  @override
  _i12.Future<_i8.IUnifediApiAccountRelationship> togglePin() =>
      (super.noSuchMethod(
        Invocation.method(
          #togglePin,
          [],
        ),
        returnValue: _i12.Future<_i8.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_6(
          this,
          Invocation.method(
            #togglePin,
            [],
          ),
        )),
      ) as _i12.Future<_i8.IUnifediApiAccountRelationship>);

  @override
  _i12.Future<_i8.IUnifediApiAccountRelationship> toggleBlock() =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleBlock,
          [],
        ),
        returnValue: _i12.Future<_i8.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_6(
          this,
          Invocation.method(
            #toggleBlock,
            [],
          ),
        )),
      ) as _i12.Future<_i8.IUnifediApiAccountRelationship>);

  @override
  _i12.Future<_i8.IUnifediApiAccountRelationship> toggleSubscribe() =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleSubscribe,
          [],
        ),
        returnValue: _i12.Future<_i8.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_6(
          this,
          Invocation.method(
            #toggleSubscribe,
            [],
          ),
        )),
      ) as _i12.Future<_i8.IUnifediApiAccountRelationship>);

  @override
  _i12.Future<_i8.IUnifediApiAccountRelationship> toggleBlockDomain() =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleBlockDomain,
          [],
        ),
        returnValue: _i12.Future<_i8.IUnifediApiAccountRelationship>.value(
            _FakeIUnifediApiAccountRelationship_6(
          this,
          Invocation.method(
            #toggleBlockDomain,
            [],
          ),
        )),
      ) as _i12.Future<_i8.IUnifediApiAccountRelationship>);

  @override
  _i12.Future<void> refreshFromNetwork(
          {required bool? isNeedPreFetchRelationship}) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshFromNetwork,
          [],
          {#isNeedPreFetchRelationship: isNeedPreFetchRelationship},
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void addDisposable(_i22.IDisposable? disposable) => super.noSuchMethod(
        Invocation.method(
          #addDisposable,
          [disposable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addDisposables(Iterable<_i22.IDisposable>? disposables) =>
      super.noSuchMethod(
        Invocation.method(
          #addDisposables,
          [disposables],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> performDispose() => (super.noSuchMethod(
        Invocation.method(
          #performDispose,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);
}

/// A class which mocks [IConnectionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIConnectionService extends _i1.Mock
    implements _i26.IConnectionService {
  MockIConnectionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Stream<_i27.ConnectivityResult> get connectionStateStream =>
      (super.noSuchMethod(
        Invocation.getter(#connectionStateStream),
        returnValue: _i12.Stream<_i27.ConnectivityResult>.empty(),
      ) as _i12.Stream<_i27.ConnectivityResult>);

  @override
  _i27.ConnectivityResult get connectionState => (super.noSuchMethod(
        Invocation.getter(#connectionState),
        returnValue: _i27.ConnectivityResult.bluetooth,
      ) as _i27.ConnectivityResult);

  @override
  _i12.Stream<bool> get isConnectedStream => (super.noSuchMethod(
        Invocation.getter(#isConnectedStream),
        returnValue: _i12.Stream<bool>.empty(),
      ) as _i12.Stream<bool>);

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  _i22.DisposeOrder get disposeOrder => (super.noSuchMethod(
        Invocation.getter(#disposeOrder),
        returnValue: _i22.DisposeOrder.lifo,
      ) as _i22.DisposeOrder);

  @override
  bool get catchExceptions => (super.noSuchMethod(
        Invocation.getter(#catchExceptions),
        returnValue: false,
      ) as bool);

  @override
  List<_i22.IDisposable> get disposables => (super.noSuchMethod(
        Invocation.getter(#disposables),
        returnValue: <_i22.IDisposable>[],
      ) as List<_i22.IDisposable>);

  @override
  bool get isDisposed => (super.noSuchMethod(
        Invocation.getter(#isDisposed),
        returnValue: false,
      ) as bool);

  @override
  set isDisposed(bool? _isDisposed) => super.noSuchMethod(
        Invocation.setter(
          #isDisposed,
          _isDisposed,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> internalAsyncInit() => (super.noSuchMethod(
        Invocation.method(
          #internalAsyncInit,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void addDisposable(_i22.IDisposable? disposable) => super.noSuchMethod(
        Invocation.method(
          #addDisposable,
          [disposable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addDisposables(Iterable<_i22.IDisposable>? disposables) =>
      super.noSuchMethod(
        Invocation.method(
          #addDisposables,
          [disposables],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> performDispose() => (super.noSuchMethod(
        Invocation.method(
          #performDispose,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);
}
