name: fedi_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.2.0+5276

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # locales & localization
  intl: ^0.19.0

  # enhanced reorderable list
  flutter_reorderable_list: ^1.3.1

  # firebase auth
  firebase_core: ^3.1.1
  # push notifications FCM
  firebase_messaging: ^15.0.2

  # handle crashes and non-fatal errors
  firebase_crashlytics: ^4.0.2

  # handle init urls. Used for login/register and navigation from notification
  uni_links: ^0.5.1

  # launch browser to view links
  url_launcher: ^6.2.6

  # object serialization
  hive:
    git:
      url: ../../packages/hive
      ref: xal/nested_type_registry_dev
      path: hive
    # git:
    #   url: https://github.com/xal/hive
    #   ref: xal/nested_type_registry_dev
    #   path: hive
  hive_flutter:
    git:
      url: ../../packages/hive
      ref: xal/nested_type_registry_dev
      path: hive_flutter
    # git:
    #   url: https://github.com/xal/hive
    #   ref: xal/nested_type_registry_dev
    #   path: hive_flutter

  # render status body, description, notes and other texts which may have html tags
  flutter_html: ^3.0.0-beta.2

  # minutes/hours picker
  # duration_picker: 1.0.1
  # it is duration_picker 1.0.1 with naming & visibility enhancments
  # duration_time_picker: ^1.0.1
  duration_picker: ^1.2.0
    # git:
      # url: https://github.com/xal/duration_picker.git
      # ref: ea2decc7d3f6cf2ebb7ff01570268045da71f647

  # media grid
  flutter_staggered_grid_view: ^0.7.0
  # retrieve storage path to save files
  path_provider: ^2.1.3
  # fetch gallery albums and items
  photo_manager: ^3.1.1
  # detect file mime type for share
  mime_type: 1.0.0
  # datetime formatter for statuses & chat messages
  timeago: ^3.6.1
  # better image viewer with gestures support
  photo_view: ^0.15.0
  # positioned list view
  scrollable_positioned_list: ^0.3.8
  # edit images during account editing
  image_cropper: ^7.1.0
  # cache images locally
  cached_network_image: ^3.3.1
  # cache manager for cached_network_image. Use to set up cache settings
  flutter_cache_manager: ^3.3.2
  # reactive programming
  rxdart: ^0.27.7
  async: ^2.11.0
  # text size to fit constraints
  auto_size_text: ^3.0.0

  # default media picker
  image_picker: ^1.1.1

  # customizable datetime picker
  # flutter_datetime_picker: 1.5.1
  # it is 1.5.1 with fixes for null-safety compile warnings
  # Realank is official author. He just didn't release new version yet
  flutter_datetime_picker_plus: ^2.2.0
    # git:
      # url: https://github.com/Realank/flutter_datetime_picker.git
      # ref: eb9701172da23121d8632369e5a6c4382bcc5e45

  # annotations to generate json from & to methods
  json_annotation: ^4.9.0

  # advanced logging
  logging: ^1.2.0

  # dependency injection framework
  provider: ^6.1.2

  # fancy permission handler
  permission_handler: ^11.3.1

  # native kotlin/swift image convert & compress
  flutter_image_compress: ^2.3.0

  # commandline script to pull database from emulator
  # adb exec-out run-as com.fediverse.app cat ./databases/jffdev@fedi.app.sqlite > database.sqlite
  # sqlite orm
  drift: ^2.18.0

  # sqlite3_flutter_libs required for moor ffi
  sqlite3_flutter_libs: ^0.5.21

  # database inspector for debugging. Use with Moor Inspector Intellij Idea Plugin
  drift_local_storage_inspector: ^0.7.0

  # check internet connection state
  connectivity_plus: ^6.0.3

  # WebSockets API mobile implementation
  web_socket_channel: ^2.4.5

  # save photo and video to gallery
  gallery_saver: 2.3.2

  # share actions via native API
  share_plus: 9.0.0

  # detect mime type be extension
  mime: ^1.0.5

  # parse html to extract raw text from status content
  html: ^0.15.4

  # better scroll controller for nested scroll
  nested_scroll_controller: 1.0.0

  # media attachments carousel
  carousel_slider: ^4.2.1

  # video/audio players
  video_player: ^2.8.6

  # pull to refresh and pull to load more
  pull_to_refresh: 2.0.0

  # custom scroll view which fix bugs related to inner scrollables sync
  # extended_nested_scroll_view >= 4.0.0 have bugs with scrollable in tabs
  # todo: update when bug will be fixed
  extended_nested_scroll_view: ^6.2.1

  # error overlay
  overlay_support: ^2.1.0

  # file picker for media attachment
  file_picker: ^8.0.3
  file: ^7.0.0

  # unenscape account not field
  html_unescape: 2.0.0

  # extended text fields with highlight mentions support
  extended_text_field: ^15.0.0

  # detect keyboard visibility
  flutter_keyboard_visibility: ^6.0.0

  # list view item slide actions
  flutter_slidable: ^3.1.0

  # disable wakelock for video player
  wakelock_plus: ^1.2.5

  # ask for review inside app
  in_app_review: ^2.0.9

  # better dateTime manipulation (especially for add duration to dateTime)
  jiffy: ^6.3.1

  # collections extensions
  collection: ^1.18.0

  # customizable switch widget
  flutter_switch: 0.3.2

  # handle external share intents (text/image/video/etc)
  # receive_sharing_intent: 1.4.5
  # it is receive_sharing_intent 779e511eb70e0c68b1a314c020c257bd102a4698 with custom_app_id fix
  receive_sharing_intent: ^1.8.0
    # git:
    #   url: https://github.com/xal/receive_sharing_intent.git
    #   ref: aee4b7c77901c2cd18d7fb4970837d83969f320f


  # load config from .env files (support flavors)
  flutter_config: ^2.0.2

  # get build details for config
  package_info_plus: ^8.0.0

  # rich notification with possible integration with FCM
  awesome_notifications: ^0.9.3+1

  # Disposable logic
  easy_dispose: 1.1.0
  easy_dispose_flutter: 1.1.0
  easy_dispose_rxdart: 1.1.0
  easy_dispose_provider: 1.1.0

  # work with path/url parts
  path: 1.9.0

  # code generator: unions, strings, equals & hash, etc
  freezed_annotation: ^2.4.1

  fediverse_api:
    path: ../../packages/fediverse_api
#    git:
#      url: https://github.com/Big-Fig/Fediverse.app.git
#      path: packages/fediverse_api

  pleroma_api:
    path: ../../packages/pleroma_api
#    git:
#      url: https://github.com/Big-Fig/Fediverse.app.git
#      path: packages/pleroma_api

  mastodon_api:
    path: ../../packages/mastodon_api
#    git:
#      url: https://github.com/Big-Fig/Fediverse.app.git
#      path: packages/mastodon_api

  unifedi_api:
    path: ../../packages/unifedi_api
#    git:
#      url: https://github.com/Big-Fig/Fediverse.app.git
#      path: packages/unifedi_api

  html_parser_plus: ^0.1.4

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

  # easy mock for tests
  mockito: 5.4.4
  # build tools runner
  # usage example
  build_runner: ^2.4.11
  # build tool to generate json from & to methods
  json_serializable: 6.8.0
  # sql orm generator
  drift_dev: ^2.18.0
  # required by sqlparser. Otherwise strange errors -
  sqlparser: ^0.36.0

  # object serialization generator
  hive_generator:
    git:
      url: ../../packages/hive
      ref: xal/nested_type_registry_dev
      path: hive_generator
    # git:
    #   url: https://github.com/xal/hive
    #   ref: xal/nested_type_registry_dev
    #   path: hive_generator

  # official linters
  lints: ^4.0.0
  flutter_lints: ^4.0.0

  # helper to specify all rules in one line
  all_lint_rules_community: ^0.0.4

  # additional linters
  # dart_code_metrics: ^4.5.0

  # generate screenshots for stores during UI tests
  # also useful for golden tests
  screenshots:
    git:
      url: https://github.com/felixgabler/screenshots
      # ref: b855c90dd78a4e5db447d003dddb84021db9411c

  # code generator: unions, strings, equals & hash, etc
  freezed: ^2.5.2

dependency_overrides: 
  # http: ^1.2.1
  # meta: ^1.15.0
  # analyzer: ^6.3.0
  # intl: ^0.18.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: FediIcons
      fonts:
        - asset: assets/fonts/FediIcons.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/server_list.txt
    - assets/terms/terms.rtf
    - assets/images/theme/logo.png
    - assets/images/default_timeline_header.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true