// Mocks generated by Mockito 5.4.4 from annotations
// in fedi_app/test/app/account/my/my_account_bloc_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:fediverse_api/fediverse_api.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:unifedi_api/src/api/account/my/edit/unifedi_api_edit_my_account_model.dart'
    as _i9;
import 'package:unifedi_api/src/api/account/my/service/unifedi_api_my_account_service.dart'
    as _i7;
import 'package:unifedi_api/src/api/account/my/unifedi_api_my_account_model.dart'
    as _i4;
import 'package:unifedi_api/src/api/account/relationship/unifedi_api_account_relationship_model.dart'
    as _i13;
import 'package:unifedi_api/src/api/account/unifedi_api_account_model.dart'
    as _i11;
import 'package:unifedi_api/src/api/feature/unifedi_api_feature_model.dart'
    as _i2;
import 'package:unifedi_api/src/api/pagination/unifedi_api_pagination_model.dart'
    as _i10;
import 'package:unifedi_api/src/api/rest/unifedi_api_rest_service.dart' as _i3;
import 'package:unifedi_api/src/api/status/unifedi_api_status_model.dart'
    as _i12;
import 'package:unifedi_api/src/api/tag/unifedi_api_tag_model.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIUnifediApiFeature_0 extends _i1.SmartFake
    implements _i2.IUnifediApiFeature {
  _FakeIUnifediApiFeature_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIUnifediApiRestService_1 extends _i1.SmartFake
    implements _i3.IUnifediApiRestService {
  _FakeIUnifediApiRestService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIUnifediApiMyAccount_2 extends _i1.SmartFake
    implements _i4.IUnifediApiMyAccount {
  _FakeIUnifediApiMyAccount_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIUnifediApiTag_3 extends _i1.SmartFake
    implements _i5.IUnifediApiTag {
  _FakeIUnifediApiTag_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFediverseApiFeatureRequirementState_4 extends _i1.SmartFake
    implements _i6.FediverseApiFeatureRequirementState {
  _FakeFediverseApiFeatureRequirementState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IUnifediApiMyAccountService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIUnifediApiMyAccountService extends _i1.Mock
    implements _i7.IUnifediApiMyAccountService {
  MockIUnifediApiMyAccountService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IUnifediApiFeature get updateMyCredentialsFeature => (super.noSuchMethod(
        Invocation.getter(#updateMyCredentialsFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#updateMyCredentialsFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get updateMyCredentialsLockedFeature =>
      (super.noSuchMethod(
        Invocation.getter(#updateMyCredentialsLockedFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#updateMyCredentialsLockedFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get updateMyCredentialsPrivacyFeature =>
      (super.noSuchMethod(
        Invocation.getter(#updateMyCredentialsPrivacyFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#updateMyCredentialsPrivacyFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get updateMyCredentialsSensitiveFeature =>
      (super.noSuchMethod(
        Invocation.getter(#updateMyCredentialsSensitiveFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#updateMyCredentialsSensitiveFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get updateMyCredentialsDiscoverableFeature =>
      (super.noSuchMethod(
        Invocation.getter(#updateMyCredentialsDiscoverableFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#updateMyCredentialsDiscoverableFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get updateMyCredentialsNoRichTextFeature =>
      (super.noSuchMethod(
        Invocation.getter(#updateMyCredentialsNoRichTextFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#updateMyCredentialsNoRichTextFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get updateMyCredentialsHideFollowersFeature =>
      (super.noSuchMethod(
        Invocation.getter(#updateMyCredentialsHideFollowersFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#updateMyCredentialsHideFollowersFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get updateMyCredentialsHideFollowsFeature =>
      (super.noSuchMethod(
        Invocation.getter(#updateMyCredentialsHideFollowsFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#updateMyCredentialsHideFollowsFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get updateMyCredentialsHideFollowersCountFeature =>
      (super.noSuchMethod(
        Invocation.getter(#updateMyCredentialsHideFollowersCountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#updateMyCredentialsHideFollowersCountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get updateMyCredentialsHideFollowsCountFeature =>
      (super.noSuchMethod(
        Invocation.getter(#updateMyCredentialsHideFollowsCountFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#updateMyCredentialsHideFollowsCountFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get updateMyCredentialsHideFavoritesFeature =>
      (super.noSuchMethod(
        Invocation.getter(#updateMyCredentialsHideFavoritesFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#updateMyCredentialsHideFavoritesFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get updateMyCredentialsShowRoleFeature =>
      (super.noSuchMethod(
        Invocation.getter(#updateMyCredentialsShowRoleFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#updateMyCredentialsShowRoleFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get updateMyCredentialsDefaultScopeFeature =>
      (super.noSuchMethod(
        Invocation.getter(#updateMyCredentialsDefaultScopeFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#updateMyCredentialsDefaultScopeFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get updateMyCredentialsSettingsStoreFeature =>
      (super.noSuchMethod(
        Invocation.getter(#updateMyCredentialsSettingsStoreFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#updateMyCredentialsSettingsStoreFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get updateMyCredentialsSkipThreadContainmentFeature =>
      (super.noSuchMethod(
        Invocation.getter(#updateMyCredentialsSkipThreadContainmentFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#updateMyCredentialsSkipThreadContainmentFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get updateMyCredentialsAllowFollowingMoveFeature =>
      (super.noSuchMethod(
        Invocation.getter(#updateMyCredentialsAllowFollowingMoveFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#updateMyCredentialsAllowFollowingMoveFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get updateMyCredentialsAcceptsChatMessagesFeature =>
      (super.noSuchMethod(
        Invocation.getter(#updateMyCredentialsAcceptsChatMessagesFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#updateMyCredentialsAcceptsChatMessagesFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get updateMyCredentialsAlsoKnownAsFeature =>
      (super.noSuchMethod(
        Invocation.getter(#updateMyCredentialsAlsoKnownAsFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#updateMyCredentialsAlsoKnownAsFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get updateMyCredentialsBackgroundImageFeature =>
      (super.noSuchMethod(
        Invocation.getter(#updateMyCredentialsBackgroundImageFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#updateMyCredentialsBackgroundImageFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get verifyMyCredentialsFeature => (super.noSuchMethod(
        Invocation.getter(#verifyMyCredentialsFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#verifyMyCredentialsFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getMyDomainBlocksFeature => (super.noSuchMethod(
        Invocation.getter(#getMyDomainBlocksFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getMyDomainBlocksFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getMyAccountBlocksFeature => (super.noSuchMethod(
        Invocation.getter(#getMyAccountBlocksFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getMyAccountBlocksFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getMyAccountMutesFeature => (super.noSuchMethod(
        Invocation.getter(#getMyAccountMutesFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getMyAccountMutesFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getMyBookmarksFeature => (super.noSuchMethod(
        Invocation.getter(#getMyBookmarksFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getMyBookmarksFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getMyFollowRequestsFeature => (super.noSuchMethod(
        Invocation.getter(#getMyFollowRequestsFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getMyFollowRequestsFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get acceptMyAccountFollowRequestFeature =>
      (super.noSuchMethod(
        Invocation.getter(#acceptMyAccountFollowRequestFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#acceptMyAccountFollowRequestFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get rejectMyAccountFollowRequestFeature =>
      (super.noSuchMethod(
        Invocation.getter(#rejectMyAccountFollowRequestFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#rejectMyAccountFollowRequestFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getMyEndorsementsFeature => (super.noSuchMethod(
        Invocation.getter(#getMyEndorsementsFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getMyEndorsementsFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getMyAccountFeaturedTagsFeature =>
      (super.noSuchMethod(
        Invocation.getter(#getMyAccountFeaturedTagsFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getMyAccountFeaturedTagsFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get featureMyAccountTagFeature => (super.noSuchMethod(
        Invocation.getter(#featureMyAccountTagFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#featureMyAccountTagFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get unfeatureMyAccountTagFeature =>
      (super.noSuchMethod(
        Invocation.getter(#unfeatureMyAccountTagFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#unfeatureMyAccountTagFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getMySuggestedTagsFeature => (super.noSuchMethod(
        Invocation.getter(#getMySuggestedTagsFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getMySuggestedTagsFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getMySuggestionsFeature => (super.noSuchMethod(
        Invocation.getter(#getMySuggestionsFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getMySuggestionsFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get removeMyAccountSuggestionFeature =>
      (super.noSuchMethod(
        Invocation.getter(#removeMyAccountSuggestionFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#removeMyAccountSuggestionFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getMyFavouritesFeature => (super.noSuchMethod(
        Invocation.getter(#getMyFavouritesFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getMyFavouritesFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getMyFavouritesPaginationMinIdFeature =>
      (super.noSuchMethod(
        Invocation.getter(#getMyFavouritesPaginationMinIdFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getMyFavouritesPaginationMinIdFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get getMyAccountMutesWithRelationshipFeature =>
      (super.noSuchMethod(
        Invocation.getter(#getMyAccountMutesWithRelationshipFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#getMyAccountMutesWithRelationshipFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i2.IUnifediApiFeature get editNotificationsSettingsFeature =>
      (super.noSuchMethod(
        Invocation.getter(#editNotificationsSettingsFeature),
        returnValue: _FakeIUnifediApiFeature_0(
          this,
          Invocation.getter(#editNotificationsSettingsFeature),
        ),
      ) as _i2.IUnifediApiFeature);

  @override
  _i3.IUnifediApiRestService get restService => (super.noSuchMethod(
        Invocation.getter(#restService),
        returnValue: _FakeIUnifediApiRestService_1(
          this,
          Invocation.getter(#restService),
        ),
      ) as _i3.IUnifediApiRestService);

  @override
  bool get isDisposed => (super.noSuchMethod(
        Invocation.getter(#isDisposed),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<_i4.IUnifediApiMyAccount> updateMyCredentials(
          {required _i9.IUnifediApiEditMyAccount? editMyAccount}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMyCredentials,
          [],
          {#editMyAccount: editMyAccount},
        ),
        returnValue: _i8.Future<_i4.IUnifediApiMyAccount>.value(
            _FakeIUnifediApiMyAccount_2(
          this,
          Invocation.method(
            #updateMyCredentials,
            [],
            {#editMyAccount: editMyAccount},
          ),
        )),
      ) as _i8.Future<_i4.IUnifediApiMyAccount>);

  @override
  _i8.Future<_i4.IUnifediApiMyAccount> verifyMyCredentials() =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyMyCredentials,
          [],
        ),
        returnValue: _i8.Future<_i4.IUnifediApiMyAccount>.value(
            _FakeIUnifediApiMyAccount_2(
          this,
          Invocation.method(
            #verifyMyCredentials,
            [],
          ),
        )),
      ) as _i8.Future<_i4.IUnifediApiMyAccount>);

  @override
  _i8.Future<List<String>> getMyDomainBlocks(
          {required _i10.IUnifediApiPagination? pagination}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyDomainBlocks,
          [],
          {#pagination: pagination},
        ),
        returnValue: _i8.Future<List<String>>.value(<String>[]),
      ) as _i8.Future<List<String>>);

  @override
  _i8.Future<List<_i11.IUnifediApiAccount>> getMyAccountBlocks(
          {required _i10.IUnifediApiPagination? pagination}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyAccountBlocks,
          [],
          {#pagination: pagination},
        ),
        returnValue: _i8.Future<List<_i11.IUnifediApiAccount>>.value(
            <_i11.IUnifediApiAccount>[]),
      ) as _i8.Future<List<_i11.IUnifediApiAccount>>);

  @override
  _i8.Future<List<_i11.IUnifediApiAccount>> getMyAccountMutes({
    required bool? withRelationship,
    required _i10.IUnifediApiPagination? pagination,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyAccountMutes,
          [],
          {
            #withRelationship: withRelationship,
            #pagination: pagination,
          },
        ),
        returnValue: _i8.Future<List<_i11.IUnifediApiAccount>>.value(
            <_i11.IUnifediApiAccount>[]),
      ) as _i8.Future<List<_i11.IUnifediApiAccount>>);

  @override
  _i8.Future<List<_i12.IUnifediApiStatus>> getMyBookmarks(
          {required _i10.IUnifediApiPagination? pagination}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyBookmarks,
          [],
          {#pagination: pagination},
        ),
        returnValue: _i8.Future<List<_i12.IUnifediApiStatus>>.value(
            <_i12.IUnifediApiStatus>[]),
      ) as _i8.Future<List<_i12.IUnifediApiStatus>>);

  @override
  _i8.Future<List<_i12.IUnifediApiStatus>> getMyFavourites(
          {required _i10.IUnifediApiPagination? pagination}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyFavourites,
          [],
          {#pagination: pagination},
        ),
        returnValue: _i8.Future<List<_i12.IUnifediApiStatus>>.value(
            <_i12.IUnifediApiStatus>[]),
      ) as _i8.Future<List<_i12.IUnifediApiStatus>>);

  @override
  _i8.Future<List<_i11.IUnifediApiAccount>> getMyFollowRequests(
          {required _i10.IUnifediApiPagination? pagination}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyFollowRequests,
          [],
          {#pagination: pagination},
        ),
        returnValue: _i8.Future<List<_i11.IUnifediApiAccount>>.value(
            <_i11.IUnifediApiAccount>[]),
      ) as _i8.Future<List<_i11.IUnifediApiAccount>>);

  @override
  _i8.Future<_i13.IUnifediApiAccountRelationship?> acceptMyAccountFollowRequest(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptMyAccountFollowRequest,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i8.Future<_i13.IUnifediApiAccountRelationship?>.value(),
      ) as _i8.Future<_i13.IUnifediApiAccountRelationship?>);

  @override
  _i8.Future<_i13.IUnifediApiAccountRelationship?> rejectMyAccountFollowRequest(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #rejectMyAccountFollowRequest,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i8.Future<_i13.IUnifediApiAccountRelationship?>.value(),
      ) as _i8.Future<_i13.IUnifediApiAccountRelationship?>);

  @override
  _i8.Future<List<_i11.IUnifediApiAccount>> getMyEndorsements(
          {required _i10.IUnifediApiPagination? pagination}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyEndorsements,
          [],
          {#pagination: pagination},
        ),
        returnValue: _i8.Future<List<_i11.IUnifediApiAccount>>.value(
            <_i11.IUnifediApiAccount>[]),
      ) as _i8.Future<List<_i11.IUnifediApiAccount>>);

  @override
  _i8.Future<List<_i5.IUnifediApiTag>> getMyAccountFeaturedTags(
          {required _i10.IUnifediApiPagination? pagination}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyAccountFeaturedTags,
          [],
          {#pagination: pagination},
        ),
        returnValue:
            _i8.Future<List<_i5.IUnifediApiTag>>.value(<_i5.IUnifediApiTag>[]),
      ) as _i8.Future<List<_i5.IUnifediApiTag>>);

  @override
  _i8.Future<List<_i5.IUnifediApiTag>> getMySuggestedTags() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMySuggestedTags,
          [],
        ),
        returnValue:
            _i8.Future<List<_i5.IUnifediApiTag>>.value(<_i5.IUnifediApiTag>[]),
      ) as _i8.Future<List<_i5.IUnifediApiTag>>);

  @override
  _i8.Future<_i5.IUnifediApiTag> featureMyAccountTag({required String? name}) =>
      (super.noSuchMethod(
        Invocation.method(
          #featureMyAccountTag,
          [],
          {#name: name},
        ),
        returnValue: _i8.Future<_i5.IUnifediApiTag>.value(_FakeIUnifediApiTag_3(
          this,
          Invocation.method(
            #featureMyAccountTag,
            [],
            {#name: name},
          ),
        )),
      ) as _i8.Future<_i5.IUnifediApiTag>);

  @override
  _i8.Future<void> unfeatureMyAccountTag({required String? tagId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #unfeatureMyAccountTag,
          [],
          {#tagId: tagId},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i11.IUnifediApiAccount>> getMySuggestions(
          {required int? limit}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMySuggestions,
          [],
          {#limit: limit},
        ),
        returnValue: _i8.Future<List<_i11.IUnifediApiAccount>>.value(
            <_i11.IUnifediApiAccount>[]),
      ) as _i8.Future<List<_i11.IUnifediApiAccount>>);

  @override
  _i8.Future<void> removeMyAccountSuggestion({required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMyAccountSuggestion,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> editNotificationsSettings({
    required bool? blockFromStrangers,
    required bool? hideNotificationContents,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #editNotificationsSettings,
          [],
          {
            #blockFromStrangers: blockFromStrangers,
            #hideNotificationContents: hideNotificationContents,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i6.FediverseApiFeatureRequirementState checkFeatureState(
          _i2.IUnifediApiFeature? feature) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkFeatureState,
          [feature],
        ),
        returnValue: _FakeFediverseApiFeatureRequirementState_4(
          this,
          Invocation.method(
            #checkFeatureState,
            [feature],
          ),
        ),
      ) as _i6.FediverseApiFeatureRequirementState);

  @override
  _i8.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}
